/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function readText(): string | null
export function readFiles(): Array<string> | null
export function readImage(): Buffer | null
export function writeText(text: string): boolean | null
export function writeFiles(files: Array<string>): boolean | null
export function writeImage(img: Buffer): boolean | null
